apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: configuracao-mongodb #mesmo nome que está em statefulset.yaml > volumes > persistentVolumeClaim > claimName
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

