apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment-api-springboot-docker-kubernetes
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: pod-api-springboot-docker-kubernetes
        tier: backend
    spec:
      containers:
        - name: container-api-springboot-docker-kubernetes
          image: nickkborges/springboot-docker-kubernetes:v3
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: GET_HOSTS_FROM
              value: dns
          ports:
            - containerPort: 8080
