apiVersion: v1
kind: Service
metadata:
  name: service-api-springboot-docker-kubernetes
  labels:
    app: service-api-springboot-docker-kubernetes
    tier: backend
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: pod-api-springboot-docker-kubernetes
    tier: backend
